//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dermasoft.core.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alergia
    {
        public int IdAlergia { get; set; }
        public int IdPaciente { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
