//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dermasoft.core.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivoImagen
    {
        public int IdArchivo { get; set; }
        public string NombreArchivo { get; set; }
        public int IdVisita { get; set; }
        public string Extension { get; set; }
        public string ContentType { get; set; }
    
        public virtual Visita Visitas { get; set; }
    }
}
