//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dermasoft.core.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DermasoftEntities : DbContext
    {
        public DermasoftEntities()
            : base("name=DermasoftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ObraSocial> ObraSocial { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<ArchivoImagen> ArchivoImagen { get; set; }
        public virtual DbSet<Alergia> Alergia { get; set; }
        public virtual DbSet<TipoNota> TipoNota { get; set; }
        public virtual DbSet<Antecedente> Antecedente { get; set; }
        public virtual DbSet<Nota> Nota { get; set; }
        public virtual DbSet<Visita> Visita { get; set; }
        public virtual DbSet<MotivoConsulta> MotivoConsulta { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
    }
}
