//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dermasoft.core.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoConsulta
    {
        public MotivoConsulta()
        {
            this.Visitas = new HashSet<Visita>();
        }
    
        public int IdMotivoConsulta { get; set; }
        public string MotivoConsulta1 { get; set; }
        public string AntecedentesEA { get; set; }
        public int IdPaciente { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Visita> Visitas { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
