//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dermasoft.core.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObraSocial
    {
        public ObraSocial()
        {
            this.Pacientes = new HashSet<Paciente>();
        }
    
        public int IdObraSocial { get; set; }
        public string NombreObraSocial { get; set; }
        public string Clave { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Paciente> Pacientes { get; set; }
    }
}
