//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dermasoft.core.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.Alergias = new HashSet<Alergia>();
            this.Antecedentes = new HashSet<Antecedente>();
            this.MotivoConsultas = new HashSet<MotivoConsulta>();
        }
    
        public int IdPaciente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Dni { get; set; }
        public int Edad { get; set; }
        public int IdObraSocial { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string NroAfiliado { get; set; }
    
        public virtual ICollection<Alergia> Alergias { get; set; }
        public virtual ICollection<Antecedente> Antecedentes { get; set; }
        public virtual ICollection<MotivoConsulta> MotivoConsultas { get; set; }
        public virtual ObraSocial ObraSocial { get; set; }
    }
}
