//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dermasoft.core.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visita
    {
        public Visita()
        {
            this.ArchivoImagen = new HashSet<ArchivoImagen>();
            this.Notas = new HashSet<Nota>();
            this.Notas1 = new HashSet<Nota>();
        }
    
        public int IdVisita { get; set; }
        public System.DateTime FechaVisita { get; set; }
        public Nullable<int> IdMotivoConsulta { get; set; }
    
        public virtual ICollection<ArchivoImagen> ArchivoImagen { get; set; }
        public virtual ICollection<Nota> Notas { get; set; }
        public virtual MotivoConsulta MotivoConsultas { get; set; }
        public virtual ICollection<Nota> Notas1 { get; set; }
    }
}
